/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CenterRouteImport } from './routes/center'
import { Route as IndexRouteImport } from './routes/index'

const CenterRoute = CenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/center': typeof CenterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/center': typeof CenterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/center': typeof CenterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/center'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/center'
  id: '__root__' | '/' | '/center'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenterRoute: typeof CenterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenterRoute: CenterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
